### PR TITLE
chore(about): Update to freeCodeCamp

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@raisedadead we want to do this against staging, right? Not Master.

**Comment by raisedadead** [comment]
Quincy, the pull request is on about page (static) repo.

**Comment by QuincyLarson** [comment]
@raisedadead OK - thanks! I somehow overlooked this fact :)

**Comment by QuincyLarson** [comment]
@raisedadead I've deployed this and it's now live. Thanks again!

**Comment by raisedadead** [comment]
Sure, happy to help!

**Pull request merged**
